In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import os
from IPython.display import display

In [2]:
sns.set(
    context="notebook",
    rc={"figure.figsize": (12, 10)},
    palette=sns.color_palette("tab10", 10),
)

In [3]:
# Updated dataset paths with 'real' and 'synth' folders
datasets = {
    'Insurance': {
        'real': '../data/raw/data/insurance/real/insurance.csv',
        'synthetic': '../data/raw/data/insurance/synth/insurance_1M.csv'
    },
    'Diabetes': {
        'real': '../data/raw/data/diabetes/real/diabetes.csv',
        'synthetic': '../data/raw/data/diabetes/synth/diabetes_100K.csv'
    },
    'EPC': {
        'real': '../data/raw/data/epc/real/epc.csv',
        'synthetic': '../data/raw/data/epc/synth/epc_100K.csv'
    },
    'Income': {
        'real': '../data/raw/data/income/real/income.csv',
        'synthetic': '../data/raw/data/income/synth/income_100K.csv'
    },
    'Pollution': {
        'real': '../data/raw/data/pollution/real/pollution.csv',
        'synthetic': '../data/raw/data/pollution/synth/pollution_1000ID.csv'
    },
    'Wine': {
        'real': '../data/raw/data/wine/real/wine.csv',
        'synthetic': '../data/raw/data/wine/synth/wine_500K.csv'
    },
    'Macroenv': {
        'real': '../data/raw/data/macroenv/real/macroenv.csv',
        'synthetic': '../data/raw/data/macroenv/synth/macroenv_10KID.csv'
    }
}

In [4]:
# Ensure figures directory exists
os.makedirs('figures', exist_ok=True)

def separate_descriptive_stats(real_df, synth_df, numeric_cols):
    # Real data
    desc_real = real_df[numeric_cols].describe().T
    desc_real = desc_real.rename(columns={
        'count': 'Count',
        'mean': 'Mean',
        'std': 'Std Dev',
        'min': 'Min',
        '50%': 'Median',
        'max': 'Max'
    })
    desc_real = desc_real[['Count', 'Mean', 'Std Dev', 'Min', 'Median', 'Max']].T
    desc_real.columns.name = None
    desc_real.index.name = 'Statistic'
    desc_real = desc_real.round(2)
    desc_real.reset_index(inplace=True)

    # Synthetic data
    desc_synth = synth_df[numeric_cols].describe().T
    desc_synth = desc_synth.rename(columns={
        'count': 'Count',
        'mean': 'Mean',
        'std': 'Std Dev',
        'min': 'Min',
        '50%': 'Median',
        'max': 'Max'
    })
    desc_synth = desc_synth[['Count', 'Mean', 'Std Dev', 'Min', 'Median', 'Max']].T
    desc_synth.columns.name = None
    desc_synth.index.name = 'Statistic'
    desc_synth = desc_synth.round(2)
    desc_synth.reset_index(inplace=True)

    return desc_real, desc_synth

In [5]:
def save_histograms(real_df, synth_df, cols, dataset_name):
    for col in cols:
        # Combine data and drop NaNs
        combined_data = pd.concat([real_df[col], synth_df[col]], ignore_index=True).dropna()
        
        # Compute range and bins
        min_val = combined_data.min()
        max_val = combined_data.max()
        
        # Calculate bin edges
        bins = np.histogram_bin_edges(combined_data, bins=30, range=(min_val, max_val))
        
        plt.figure(figsize=(8, 4))
        
        sns.histplot(
            real_df[col].dropna(), 
            color='blue', 
            label='Real', 
            stat='density', 
            kde=True, 
            bins=bins, 
            alpha=0.5
        )
        
        sns.histplot(
            synth_df[col].dropna(), 
            color='red', 
            label='Synthetic', 
            stat='density', 
            kde=True, 
            bins=bins, 
            alpha=0.5
        )
        
        plt.title(f'{dataset_name} - {col} Distribution')
        plt.legend(loc='upper right')
        plt.tight_layout()
        plt.savefig(f'figures/{dataset_name}_{col}_hist.png')
        plt.close()

In [6]:
def save_violin_plots(real_df, synth_df, cols, dataset_name):
    for col in cols:
        fig, axes = plt.subplots(nrows=1, ncols=2, figsize=(10, 4))  # Removed sharey=True

        # Real data violin plot
        sns.violinplot(
            y=real_df[col].dropna(),
            ax=axes[0],
            color='blue',
            inner='box',
            cut=0
        )
        axes[0].set_title('Real Data')
        axes[0].set_xlabel('')
        axes[0].set_ylabel(col)
        sns.despine(ax=axes[0], top=True, right=True)  # Remove spines

        # Synthetic data violin plot
        sns.violinplot(
            y=synth_df[col].dropna(),
            ax=axes[1],
            color='red',
            inner='box',
            cut=0
        )
        axes[1].set_title('Synthetic Data')
        axes[1].set_xlabel('')
        axes[1].set_ylabel('')
        sns.despine(ax=axes[1], top=True, right=True)  # Remove spines

        # Overall plot title
        fig.suptitle(f'{dataset_name} - {col} Violin Plots', fontsize=14)
        plt.tight_layout(rect=[0, 0, 1, 0.95])
        plt.savefig(f'figures/{dataset_name}_{col}_violin.png')        
        plt.close()

In [7]:
def save_heatmap(df, cols, dataset_name, data_type):
    corr = df[cols].corr()
    plt.figure(figsize=(10,8))
    sns.heatmap(corr, annot=True, fmt='.2f', cmap='coolwarm', square=True)
    plt.title(f'{dataset_name} - Correlation Heatmap ({data_type})')
    plt.tight_layout()
    plt.savefig(f'figures/{dataset_name}_{data_type}_heatmap.png')
    plt.close()

In [8]:
def anomaly_detection_all_numeric(real_df, synth_df):
    anomalies = {}
    
    numeric_cols_real = real_df.select_dtypes(include=['number']).columns
    numeric_cols_synth = synth_df.select_dtypes(include=['number']).columns    
    
    # Only proceed with columns present in both
    numeric_cols = set(numeric_cols_real).intersection(numeric_cols_synth)
    
    total_synth = len(synth_df)   
    
    for col in sorted(numeric_cols):
        real_min = real_df[col].min()
        real_max = real_df[col].max()
        synth_col = synth_df[col]
        
        below_min_count = (synth_col < real_min).sum()
        above_max_count = (synth_col > real_max).sum()
        neg_count = (synth_col < 0).sum()        
        
        if below_min_count > 0:
            anomalies[f'{col} below real min ({real_min})'] = (
                int(below_min_count),
                round((below_min_count / total_synth) * 100, 2)
            )
            
        if above_max_count > 0:
            anomalies[f'{col} above real max ({real_max})'] = (
                int(above_max_count),
                round((above_max_count / total_synth) * 100, 2)
            )
        
        # Only flag negatives if real min >= 0 (non-negative variable)
        if real_min >= 0 and neg_count > 0:
            anomalies[f'{col} negative values'] = (
                int(neg_count),
                round((neg_count / total_synth) * 100, 2)
            )
    
    return anomalies

In [9]:
x= pd.read_csv('../data/raw/data/diabetes/real/diabetes.csv')
y=pd.read_csv('../data/raw/data/diabetes/synth/diabetes_100k.csv')

In [10]:
cat_cols_real = x.select_dtypes(include=['object', 'category']).columns.tolist()
cat_cols_synth = y.select_dtypes(include=['object', 'category']).columns.tolist()
cat_cols = list(set(cat_cols_real).intersection(cat_cols_synth))

In [11]:
for name, paths in datasets.items():
    print(f"\n\n=== Analyzing {name} Dataset ===")
    
    # Read data
    real_df = pd.read_csv(paths['real'])
    synth_df = pd.read_csv(paths['synthetic'])

    print(f"Dimension of real data: {real_df.shape}")
    print(f"Dimension of synthetic data: {synth_df.shape}")
    
    # Detect numeric columns
    numeric_cols_real = real_df.select_dtypes(include=['number']).columns.tolist()
    numeric_cols_synth = synth_df.select_dtypes(include=['number']).columns.tolist()
    numeric_cols = list(set(numeric_cols_real).intersection(set(numeric_cols_synth)))
    
    # ✅ Sort columns alphabetically
    numeric_cols.sort()
    
    print(f"Numeric columns detected ({len(numeric_cols)}): {numeric_cols}")
    
    # --- Metadata Comparison ---
    # Get dtypes for all columns in both datasets
    real_dtypes = real_df.dtypes.astype(str)
    synth_dtypes = synth_df.dtypes.astype(str)

    # Create comparison DataFrame
    meta_df = pd.DataFrame({
        'Real_dtype': real_dtypes,
        'Synthetic_dtype': synth_dtypes
    })
    meta_df.reset_index(inplace=True)
    meta_df.rename(columns={'index': 'Variable'}, inplace=True)

    # Add a check if types match
    meta_df['Type_Match'] = meta_df['Real_dtype'] == meta_df['Synthetic_dtype']
    
    # Check expanded ranges
    minmax_data = []
    for col in numeric_cols:
        real_min = real_df[col].min()
        real_max = real_df[col].max()
        synth_min = synth_df[col].min()
        synth_max = synth_df[col].max()
        expanded_range = (synth_min < real_min) or (synth_max > real_max)
        
        minmax_data.append({
            'Variable': col,
            'Real_Min': real_min,
            'Real_Max': real_max,
            'Synthetic_Min': synth_min,
            'Synthetic_Max': synth_max,
            'Range_Expanded': expanded_range
        })

    range_df = pd.DataFrame(minmax_data)
    
    # Display metadata comparison
    print("\n-- Metadata Comparison --")
    display(meta_df)
    
    # Display range comparison
    print("\n-- Range Comparison for Numeric Variables --")
    display(range_df)

    # Print textual metadata summary
    num_numeric = len(numeric_cols)
    num_binary = sum(real_df[col].nunique() == 2 for col in numeric_cols)
    print(f"\nMetadata Summary:")
    print(f"• Both datasets contain:")
    print(f"  o {num_numeric} numeric variables")
    print(f"  o {num_binary} binary outcome variable(s)")
    
    if meta_df['Type_Match'].all():
        print("• Variable types are identical (floats or integers).")
    else:
        mismatches = meta_df[~meta_df['Type_Match']]
        print("• WARNING: Some variable types differ between real and synthetic datasets!")
        print(mismatches.to_string(index=False))

    if range_df['Range_Expanded'].any():
        expanded_vars = range_df[range_df['Range_Expanded']]['Variable'].tolist()
        print(f"• The synthetic dataset expands the range of the following variable(s): {expanded_vars}")
    else:
        print("• The synthetic dataset does NOT expand variable ranges compared to the real data.")
    
    # descriptive statistics    
    desc_real, desc_synth = separate_descriptive_stats(real_df, synth_df, numeric_cols)

    print("\n-- Real Data Descriptive Statistics --")
    display(desc_real)            

    print("\n-- Synthetic Data Descriptive Statistics --")
    display(desc_synth)

    # --- Categorical Variable Distributions ---
    print("\n-- Categorical Variable Distributions --")

    # Detect categorical columns
    cat_cols_real = real_df.select_dtypes(include=['object', 'category']).columns.tolist()
    cat_cols_synth = synth_df.select_dtypes(include=['object', 'category']).columns.tolist()
    cat_cols = list(set(cat_cols_real).intersection(cat_cols_synth))
    cat_cols.sort()

    if cat_cols:
        for col in cat_cols:
            print(f"\n>> Variable: {col}")

            real_counts = real_df[col].value_counts()
            real_perc = real_df[col].value_counts(normalize=True).mul(100).round(2)
            
            synth_counts = synth_df[col].value_counts()
            synth_perc = synth_df[col].value_counts(normalize=True).mul(100).round(2)

            # Align categories
            idx = real_counts.index.union(synth_counts.index)
    
            real_counts = real_counts.reindex(idx, fill_value=0)
            real_perc   = real_perc.reindex(idx, fill_value=0.0)
            synth_counts = synth_counts.reindex(idx, fill_value=0)
            synth_perc   = synth_perc.reindex(idx, fill_value=0.0)
    
            # combine per metric
            counts = pd.concat([real_counts, synth_counts], axis=1, keys=['Real', 'Synthetic'])
            props  = pd.concat([real_perc, synth_perc], axis=1, keys=['Real', 'Synthetic'])
    
            # combine metrics with MultiIndex — first level = metric, second level = dataset
            combined = pd.concat([counts, props], axis=1, keys=['Count', 'Percentage(%)'])
    
            combined.index.name = col
            combined = combined.sort_index()          

            
            display(combined)
    else:
        print("No shared categorical variables found in both datasets.")

          
    # Anomaly detection
    anomalies = anomaly_detection_all_numeric(real_df, synth_df)
    print("\n-- Anomalies Detected Across All Numeric Columns --")
    if anomalies:
        anomalies_df = pd.DataFrame(
            [(k, v[0], v[1]) for k, v in anomalies.items()],
            columns=['Anomaly', 'Count', 'Percent']
        )
        display(anomalies_df)          
    else:
        print("No anomalies detected.")
    
    # Save histograms
    print("\n-- Generating Histograms --")
    save_histograms(real_df, synth_df, numeric_cols, name)

    # Violin Plots
    print("-- Generating Violin Plots --")
    save_violin_plots(real_df, synth_df, numeric_cols, name)
    
    # Save heatmaps
    print("-- Generating Heatmaps --")
    save_heatmap(real_df, numeric_cols, name, 'Real')
    save_heatmap(synth_df, numeric_cols, name, 'Synthetic')

=== Analyzing Insurance Dataset ===
Dimension of real data: (1338, 7)
Dimension of synthetic data: (1000000, 7)
Numeric columns detected (4): ['AGE', 'BMI', 'CHARGES', 'CHILDREN']

-- Metadata Comparison --

   Variable Real_dtype Synthetic_dtype  Type_Match
0       AGE      int64         float64       False
1       SEX     object          object        True
2       BMI    float64         float64        True
3  CHILDREN      int64           int64        True
4    SMOKER     object          object        True
5    REGION     object          object        True
6   CHARGES    float64         float64        True

-- Range Comparison for Numeric Variables --

,Variable,Real_Min,Real_Max,Synthetic_Min,Synthetic_Max,Range_Expanded
0,AGE,18.0000,64.00000,10.829939,73.049334,True
1,BMI,15.9600,53.13000,12.464947,57.995008,True
2,CHARGES,1121.8739,63770.42801,-2495.680369,65486.244230,True
3,CHILDREN,0.0000,5.00000,0.000000,5.000000,False

Metadata Summary:
• Both datasets contain:
  o 4 numeric variables
  o 0 binary outcome variable(s)
• WARNING: Some variable types differ between real and synthetic datasets!
Variable Real_dtype Synthetic_dtype  Type_Match
     AGE      int64         float64       False
• The synthetic dataset expands the range of the following variable(s): ['AGE', 'BMI', 'CHARGES']

-- Real Data Descriptive Statistics --

  Statistic      AGE      BMI   CHARGES  CHILDREN
0     Count  1338.00  1338.00   1338.00   1338.00
1      Mean    39.21    30.66  13270.42      1.09
2   Std Dev    14.05     6.10  12110.01      1.21
3       Min    18.00    15.96   1121.87      0.00
4    Median    39.00    30.40   9382.03      1.00
5       Max    64.00    53.13  63770.43      5.00

-- Synthetic Data Descriptive Statistics --

  Statistic         AGE         BMI     CHARGES    CHILDREN
0     Count  1000000.00  1000000.00  1000000.00  1000000.00
1      Mean       39.54       30.61    13545.84        1.30
2   Std Dev       13.97        6.23    12373.84        1.52
3       Min       10.83       12.46    -2495.68        0.00
4    Median       39.76       30.25     9573.38        1.00
5       Max       73.05       58.00    65486.24        5.00

-- Categorical Variable Distributions --

>> Variable: REGION

          Count           Percentage(%)
           Real Synthetic          Real Synthetic
REGION
northeast   324    243521         24.22     24.35
northwest   325    244332         24.29     24.43
southeast   364    268716         27.20     26.87
southwest   325    243431         24.29     24.34

>> Variable: SEX

       Count           Percentage(%)
        Real Synthetic          Real Synthetic
SEX
female   662    518001         49.48      51.8
male     676    481999         50.52      48.2

>> Variable: SMOKER

       Count           Percentage(%)
        Real Synthetic          Real Synthetic
SMOKER
no      1064    797380         79.52     79.74
yes      274    202620         20.48     20.26

-- Anomalies Detected Across All Numeric Columns --

                                Anomaly  Count  Percent
0               AGE below real min (18)  29608     2.96
1               AGE above real max (64)  18748     1.87
2            BMI below real min (15.96)   1227     0.12
3            BMI above real max (53.13)    311     0.03
4    CHARGES below real min (1121.8739)  22386     2.24
5  CHARGES above real max (63770.42801)      9     0.00
6               CHARGES negative values   4453     0.45

-- Generating Histograms --
-- Generating Violin Plots --
-- Generating Heatmaps --


=== Analyzing Diabetes Dataset ===
Dimension of real data: (768, 9)
Dimension of synthetic data: (100000, 9)
Numeric columns detected (9): ['Age', 'BMI', 'BloodPressure', 'DiabetesPedigreeFunction', 'Glucose', 'Insulin', 'Outcome', 'Pregnancies', 'SkinThickness']

-- Metadata Comparison --

                   Variable Real_dtype Synthetic_dtype  Type_Match
0               Pregnancies      int64         float64       False
1                   Glucose      int64         float64       False
2             BloodPressure      int64         float64       False
3             SkinThickness      int64         float64       False
4                   Insulin      int64         float64       False
5                       BMI    float64         float64        True
6  DiabetesPedigreeFunction    float64         float64        True
7                       Age      int64         float64       False
8                   Outcome      int64           int64        True

-- Range Comparison for Numeric Variables --

,Variable,Real_Min,Real_Max,Synthetic_Min,Synthetic_Max,Range_Expanded
0,Age,21.000,81.00,15.402254,86.276286,True
1,BMI,0.000,67.10,-26.262070,64.983679,True
2,BloodPressure,0.000,122.00,-37.477806,124.377074,True
3,DiabetesPedigreeFunction,0.078,2.42,-0.313602,3.407718,True
4,Glucose,0.000,199.00,-103.750109,229.974219,True
5,Insulin,0.000,846.00,-23.667598,891.916665,True
6,Outcome,0.000,1.00,0.000000,1.000000,False
7,Pregnancies,0.000,17.00,-1.838557,17.367333,True
8,SkinThickness,0.000,99.00,-3.489712,70.692058,True

Metadata Summary:
• Both datasets contain:
  o 9 numeric variables
  o 1 binary outcome variable(s)
• WARNING: Some variable types differ between real and synthetic datasets!
     Variable Real_dtype Synthetic_dtype  Type_Match
  Pregnancies      int64         float64       False
      Glucose      int64         float64       False
BloodPressure      int64         float64       False
SkinThickness      int64         float64       False
      Insulin      int64         float64       False
          Age      int64         float64       False
• The synthetic dataset expands the range of the following variable(s): ['Age', 'BMI', 'BloodPressure', 'DiabetesPedigreeFunction', 'Glucose', 'Insulin', 'Pregnancies', 'SkinThickness']

-- Real Data Descriptive Statistics --

,Statistic,Age,BMI,BloodPressure,DiabetesPedigreeFunction,Glucose,Insulin,Outcome,Pregnancies,SkinThickness
0,Count,768.00,768.00,768.00,768.00,768.00,768.00,768.00,768.00,768.00
1,Mean,33.24,31.99,69.11,0.47,120.89,79.80,0.35,3.85,20.54
2,Std Dev,11.76,7.88,19.36,0.33,31.97,115.24,0.48,3.37,15.95
3,Min,21.00,0.00,0.00,0.08,0.00,0.00,0.00,0.00,0.00
4,Median,29.00,32.00,72.00,0.37,117.00,30.50,0.00,3.00,23.00
5,Max,81.00,67.10,122.00,2.42,199.00,846.00,1.00,17.00,99.00

-- Synthetic Data Descriptive Statistics --

,Statistic,Age,BMI,BloodPressure,DiabetesPedigreeFunction,Glucose,Insulin,Outcome,Pregnancies,SkinThickness
0,Count,100000.00,100000.00,100000.00,100000.00,100000.00,100000.00,100000.00,100000.00,100000.00
1,Mean,33.22,31.92,69.03,0.47,122.26,81.25,0.49,3.99,20.33
2,Std Dev,11.60,7.93,18.84,0.34,32.05,115.40,0.50,3.36,15.21
3,Min,15.40,-26.26,-37.48,-0.31,-103.75,-23.67,0.00,-1.84,-3.49
4,Median,29.36,31.86,71.39,0.36,117.55,32.77,0.00,3.15,23.32
5,Max,86.28,64.98,124.38,3.41,229.97,891.92,1.00,17.37,70.69

-- Categorical Variable Distributions --
No shared categorical variables found in both datasets.

-- Anomalies Detected Across All Numeric Columns --

                                            Anomaly  Count  Percent
0                           Age below real min (21)   5667     5.67
1                           Age above real max (81)      5     0.00
2                          BMI below real min (0.0)    795     0.80
3                               BMI negative values    795     0.80
4                  BloodPressure below real min (0)   1964     1.96
5                BloodPressure above real max (122)      5     0.00
6                     BloodPressure negative values   1964     1.96
7   DiabetesPedigreeFunction below real min (0.078)   1037     1.04
8    DiabetesPedigreeFunction above real max (2.42)    224     0.22
9          DiabetesPedigreeFunction negative values     30     0.03
10                       Glucose below real min (0)    203     0.20
11                     Glucose above real max (199)   1089     1.09
12                          Glucose negative values    203     0.20
13                       Insulin below real min (0)  25500    25.50
14                     Insulin above real max (846)     10     0.01
15                          Insulin negative values  25500    25.50
16                   Pregnancies below real min (0)   4559     4.56
17                  Pregnancies above real max (17)      5     0.00
18                      Pregnancies negative values   4559     4.56
19                 SkinThickness below real min (0)  15145    15.14
20                    SkinThickness negative values  15145    15.14

-- Generating Histograms --
-- Generating Violin Plots --
-- Generating Heatmaps --


=== Analyzing EPC Dataset ===
Dimension of real data: (1000, 53)
Dimension of synthetic data: (100000, 48)
Numeric columns detected (27): ['CO2_EMISSIONS_CURRENT', 'CO2_EMISSIONS_POTENTIAL', 'CURRENT_ENERGY_EFFICIENCY', 'EXTENSION_COUNT', 'LAT', 'LIGHTING_DESCRIPTION', 'LONG', 'LOW_ENERGY_LIGHTING', 'MAIN_HEATING_CONTROLS', 'MULTI_GLAZE_PROPORTION', 'NB_MEAN_CO2_EMISSIONS_CURRENT', 'NB_MEAN_CURRENT_ENERGY_EFFICIENCY', 'NB_MEAN_CURRENT_ENERGY_RATING', 'NB_MEAN_POTENTIAL_ENERGY_EFFICIENCY', 'NB_MEAN_POTENTIAL_ENERGY_RATING', 'NB_SD_CO2_EMISSIONS_CURRENT', 'NB_SD_CURRENT_ENERGY_EFFICIENCY', 'NB_SD_CURRENT_ENERGY_RATING', 'NB_SD_POTENTIAL_ENERGY_EFFICIENCY', 'NB_SD_POTENTIAL_ENERGY_RATING', 'NUMBER_HABITABLE_ROOMS', 'NUMBER_HEATED_ROOMS', 'NUMBER_OPEN_FIREPLACES', 'POSTCODE_LAT', 'POSTCODE_LONG', 'POTENTIAL_ENERGY_EFFICIENCY', 'TOTAL_FLOOR_AREA']

-- Metadata Comparison --

                               Variable Real_dtype Synthetic_dtype  Type_Match
0                            BUILT_FORM     object          object        True
1                 CO2_EMISSIONS_CURRENT    float64         float64        True
2               CO2_EMISSIONS_POTENTIAL    float64         float64        True
3                          CONSTITUENCY     object             NaN       False
4                 CONSTRUCTION_AGE_BAND     object          object        True
5             CURRENT_ENERGY_EFFICIENCY    float64         float64        True
6                 CURRENT_ENERGY_RATING     object          object        True
7                         ENERGY_TARIFF     object          object        True
8                       EXTENSION_COUNT    float64         float64        True
9                     FLOOR_DESCRIPTION     object          object        True
10                          GLAZED_AREA     object          object        True
11                          GLAZED_TYPE     object          object        True
12                 HOTWATER_DESCRIPTION     object          object        True
13                                  LAT    float64         float64        True
14                 LIGHTING_DESCRIPTION    float64         float64        True
15                      LOCAL_AUTHORITY     object             NaN       False
16                       LODGEMENT_DATE      int64             NaN       False
17                                 LONG    float64         float64        True
18                  LOW_ENERGY_LIGHTING    float64         float64        True
19             MAINHEATCONT_DESCRIPTION     object          object        True
20                 MAINHEAT_DESCRIPTION     object          object        True
21                       MAINS_GAS_FLAG       bool            bool        True
22                            MAIN_FUEL     object          object        True
23                MAIN_HEATING_CONTROLS    float64         float64        True
24               MECHANICAL_VENTILATION     object          object        True
25               MULTI_GLAZE_PROPORTION    float64         float64        True
26        NB_MEAN_CO2_EMISSIONS_CURRENT    float64         float64        True
27    NB_MEAN_CURRENT_ENERGY_EFFICIENCY    float64         float64        True
28        NB_MEAN_CURRENT_ENERGY_RATING    float64         float64        True
29  NB_MEAN_POTENTIAL_ENERGY_EFFICIENCY    float64         float64        True
30      NB_MEAN_POTENTIAL_ENERGY_RATING    float64         float64        True
31          NB_SD_CO2_EMISSIONS_CURRENT    float64         float64        True
32      NB_SD_CURRENT_ENERGY_EFFICIENCY    float64         float64        True
33          NB_SD_CURRENT_ENERGY_RATING    float64         float64        True
34    NB_SD_POTENTIAL_ENERGY_EFFICIENCY    float64         float64        True
35        NB_SD_POTENTIAL_ENERGY_RATING    float64         float64        True
36               NUMBER_HABITABLE_ROOMS    float64         float64        True
37                  NUMBER_HEATED_ROOMS    float64         float64        True
38               NUMBER_OPEN_FIREPLACES    float64           int64       False
39                         POSTCODE_LAT    float64         float64        True
40                        POSTCODE_LONG    float64         float64        True
41                         POSTCODE_OUT     object             NaN       False
42                             POSTTOWN     object          object        True
43          POTENTIAL_ENERGY_EFFICIENCY    float64         float64        True
44              POTENTIAL_ENERGY_RATING     object          object        True
45                        PROPERTY_TYPE     object          object        True
46                     ROOF_DESCRIPTION     object          object        True
47             SOLAR_WATER_HEATING_FLAG       bool            bool        True
48                               TENURE     object          object        True
49                     TOTAL_FLOOR_AREA    float64         float64        True
50                    WALLS_DESCRIPTION     object          object        True
51                  WINDOWS_DESCRIPTION     object          object        True
52                    WIND_TURBINE_FLAG       bool             NaN       False

-- Range Comparison for Numeric Variables --

,Variable,Real_Min,Real_Max,Synthetic_Min,Synthetic_Max,Range_Expanded
0,CO2_EMISSIONS_CURRENT,0.200000,21.600000,-1.293310,27.917776,True
1,CO2_EMISSIONS_POTENTIAL,-1.600000,10.000000,-3.496741,14.537059,True
2,CURRENT_ENERGY_EFFICIENCY,2.000000,93.000000,-10.275506,95.469937,True
3,EXTENSION_COUNT,0.000000,4.000000,0.000000,4.000000,False
4,LAT,-5.210900,1.739500,-6.765665,2.710174,True
5,LIGHTING_DESCRIPTION,0.000000,100.000000,-33.093226,105.025092,True
6,LONG,50.124199,55.826302,49.745456,56.450595,True
7,LOW_ENERGY_LIGHTING,0.000000,100.000000,-34.271568,105.161989,True
8,MAIN_HEATING_CONTROLS,2101.000000,2706.000000,2090.898696,2783.810709,True
9,MULTI_GLAZE_PROPORTION,0.000000,100.000000,-39.597149,101.682377,True
10,NB_MEAN_CO2_EMISSIONS_CURRENT,0.700000,33.000000,-0.228847,23.574213,True
11,NB_MEAN_CURRENT_ENERGY_EFFICIENCY,1.000000,85.000000,-11.927070,94.454120,True
12,NB_MEAN_CURRENT_ENERGY_RATING,1.000000,6.000000,1.000000,6.000000,False
13,NB_MEAN_POTENTIAL_ENERGY_EFFICIENCY,1.000000,120.000000,-17.670424,131.164883,True
14,NB_MEAN_POTENTIAL_ENERGY_RATING,0.000000,6.000000,0.000000,6.000000,False
15,NB_SD_CO2_EMISSIONS_CURRENT,0.000000,19.798990,-13.060788,30.837085,True
16,NB_SD_CURRENT_ENERGY_EFFICIENCY,0.000000,42.426407,-5.130290,52.052923,True
17,NB_SD_CURRENT_ENERGY_RATING,0.000000,2.121320,0.000000,2.121320,True
18,NB_SD_POTENTIAL_ENERGY_EFFICIENCY,0.000000,53.740116,-22.083074,93.148111,True
19,NB_SD_POTENTIAL_ENERGY_RATING,0.000000,2.828427,0.000000,2.828427,False
20,NUMBER_HABITABLE_ROOMS,1.000000,10.000000,1.000000,10.000000,False
21,NUMBER_HEATED_ROOMS,0.000000,10.000000,0.000000,10.000000,False
22,NUMBER_OPEN_FIREPLACES,0.000000,3.000000,0.000000,3.000000,False
23,POSTCODE_LAT,-5.210900,1.739500,-6.717328,2.592549,True
24,POSTCODE_LONG,50.124199,55.826302,49.657752,56.326220,True
25,POTENTIAL_ENERGY_EFFICIENCY,42.000000,120.000000,29.410217,142.026729,True
26,TOTAL_FLOOR_AREA,14.000000,651.000000,-9.758109,444.157173,True

Metadata Summary:
• Both datasets contain:
  o 27 numeric variables
  o 0 binary outcome variable(s)
• WARNING: Some variable types differ between real and synthetic datasets!
              Variable Real_dtype Synthetic_dtype  Type_Match
          CONSTITUENCY     object             NaN       False
       LOCAL_AUTHORITY     object             NaN       False
        LODGEMENT_DATE      int64             NaN       False
NUMBER_OPEN_FIREPLACES    float64           int64       False
          POSTCODE_OUT     object             NaN       False
     WIND_TURBINE_FLAG       bool             NaN       False
• The synthetic dataset expands the range of the following variable(s): ['CO2_EMISSIONS_CURRENT', 'CO2_EMISSIONS_POTENTIAL', 'CURRENT_ENERGY_EFFICIENCY', 'LAT', 'LIGHTING_DESCRIPTION', 'LONG', 'LOW_ENERGY_LIGHTING', 'MAIN_HEATING_CONTROLS', 'MULTI_GLAZE_PROPORTION', 'NB_MEAN_CO2_EMISSIONS_CURRENT', 'NB_MEAN_CURRENT_ENERGY_EFFICIENCY', 'NB_MEAN_POTENTIAL_ENERGY_EFFICIENCY', 'NB_SD_CO2_EMISSIONS_CURRENT', 'NB_SD_CURRENT_ENERGY_EFFICIENCY', 'NB_SD_CURRENT_ENERGY_RATING', 'NB_SD_POTENTIAL_ENERGY_EFFICIENCY', 'POSTCODE_LAT', 'POSTCODE_LONG', 'POTENTIAL_ENERGY_EFFICIENCY', 'TOTAL_FLOOR_AREA']

-- Real Data Descriptive Statistics --

,Statistic,CO2_EMISSIONS_CURRENT,CO2_EMISSIONS_POTENTIAL,CURRENT_ENERGY_EFFICIENCY,EXTENSION_COUNT,LAT,LIGHTING_DESCRIPTION,LONG,LOW_ENERGY_LIGHTING,MAIN_HEATING_CONTROLS,...,NB_SD_CURRENT_ENERGY_RATING,NB_SD_POTENTIAL_ENERGY_EFFICIENCY,NB_SD_POTENTIAL_ENERGY_RATING,NUMBER_HABITABLE_ROOMS,NUMBER_HEATED_ROOMS,NUMBER_OPEN_FIREPLACES,POSTCODE_LAT,POSTCODE_LONG,POTENTIAL_ENERGY_EFFICIENCY,TOTAL_FLOOR_AREA
0,Count,1000.00,1000.00,1000.00,1000.00,1000.00,1000.00,1000.00,1000.00,1000.00,...,1000.00,1000.00,1000.00,1000.00,1000.00,1000.00,1000.00,1000.00,1000.00,1000.00
1,Mean,3.50,1.81,66.73,0.50,-1.29,76.52,52.35,76.54,2173.11,...,0.42,5.05,0.39,4.17,4.10,0.08,-1.29,52.35,81.94,86.82
2,Std Dev,2.42,1.25,13.25,0.71,1.27,31.01,1.16,30.94,109.79,...,0.44,5.87,0.47,1.57,1.59,0.31,1.27,1.16,7.67,48.81
3,Min,0.20,-1.60,2.00,0.00,-5.21,0.00,50.12,0.00,2101.00,...,0.00,0.00,0.00,1.00,0.00,0.00,-5.21,50.12,42.00,14.00
4,Median,3.00,1.50,68.00,0.00,-1.34,100.00,52.11,100.00,2173.11,...,0.42,4.24,0.39,4.00,4.00,0.00,-1.34,52.11,82.00,77.00
5,Max,21.60,10.00,93.00,4.00,1.74,100.00,55.83,100.00,2706.00,...,2.12,53.74,2.83,10.00,10.00,3.00,1.74,55.83,120.00,651.00

-- Synthetic Data Descriptive Statistics --

,Statistic,CO2_EMISSIONS_CURRENT,CO2_EMISSIONS_POTENTIAL,CURRENT_ENERGY_EFFICIENCY,EXTENSION_COUNT,LAT,LIGHTING_DESCRIPTION,LONG,LOW_ENERGY_LIGHTING,MAIN_HEATING_CONTROLS,...,NB_SD_CURRENT_ENERGY_RATING,NB_SD_POTENTIAL_ENERGY_EFFICIENCY,NB_SD_POTENTIAL_ENERGY_RATING,NUMBER_HABITABLE_ROOMS,NUMBER_HEATED_ROOMS,NUMBER_OPEN_FIREPLACES,POSTCODE_LAT,POSTCODE_LONG,POTENTIAL_ENERGY_EFFICIENCY,TOTAL_FLOOR_AREA
0,Count,100000.00,100000.00,100000.00,100000.00,100000.00,100000.00,100000.00,100000.00,100000.00,...,100000.00,100000.00,100000.00,100000.00,100000.00,100000.00,100000.00,100000.00,100000.00,100000.00
1,Mean,3.93,1.97,65.42,0.54,-1.34,76.17,52.32,75.65,2189.68,...,0.46,5.81,0.44,4.22,4.18,0.12,-1.35,52.33,81.75,92.19
2,Std Dev,3.27,1.65,16.40,0.74,1.43,31.39,1.20,31.80,129.41,...,0.48,7.90,0.54,1.67,1.69,0.39,1.39,1.19,8.71,54.76
3,Min,-1.29,-3.50,-10.28,0.00,-6.77,-33.09,49.75,-34.27,2090.90,...,0.00,-22.08,0.00,1.00,0.00,0.00,-6.72,49.66,29.41,-9.76
4,Median,3.17,1.63,67.92,0.50,-1.26,95.81,51.97,94.16,2171.22,...,0.42,4.40,0.39,4.17,4.10,0.00,-1.30,52.03,82.24,80.53
5,Max,27.92,14.54,95.47,4.00,2.71,105.03,56.45,105.16,2783.81,...,2.12,93.15,2.83,10.00,10.00,3.00,2.59,56.33,142.03,444.16

-- Categorical Variable Distributions --

>> Variable: BUILT_FORM

                     Count           Percentage(%)
                      Real Synthetic          Real Synthetic
BUILT_FORM
detached               249     25630          24.9     25.63
enclosed end-terrace    11      1323           1.1      1.32
enclosed mid-terrace    14      1993           1.4      1.99
end-terrace            132     13249          13.2     13.25
mid-terrace            287     27110          28.7     27.11
semi-detached          307     30695          30.7     30.70

>> Variable: CONSTRUCTION_AGE_BAND

                                Count           Percentage(%)
                                 Real Synthetic          Real Synthetic
CONSTRUCTION_AGE_BAND
2020                                5       421           0.5      0.42
2021                               20      3250           2.0      3.25
2022                                2        69           0.2      0.07
england and wales: 1900-1929      291     27991          29.1     27.99
england and wales: 1930-1949      118     11070          11.8     11.07
england and wales: 1950-1966      135     12465          13.5     12.46
england and wales: 1967-1975       96      8682           9.6      8.68
england and wales: 1976-1982       62      7087           6.2      7.09
england and wales: 1983-1990       57      5821           5.7      5.82
england and wales: 1991-1995       35      3378           3.5      3.38
england and wales: 1996-2002       33      2986           3.3      2.99
england and wales: 2003-2006       37      3459           3.7      3.46
england and wales: 2007 onwards    19      1906           1.9      1.91
england and wales: 2007-2011       14      2169           1.4      2.17
england and wales: before 1900     76      9246           7.6      9.25

>> Variable: CURRENT_ENERGY_RATING

                      Count           Percentage(%)
                       Real Synthetic          Real Synthetic
CURRENT_ENERGY_RATING
a                         3       181           0.3      0.18
b                       153     18690          15.3     18.69
c                       339     29611          33.9     29.61
d                       358     32408          35.8     32.41
e                       113     13612          11.3     13.61
f                        29      4585           2.9      4.58
g                         5       913           0.5      0.91

>> Variable: ENERGY_TARIFF

                 Count           Percentage(%)
                  Real Synthetic          Real Synthetic
ENERGY_TARIFF
24 hour              1       104           0.1      0.10
dual               104     12686          10.4     12.69
dual (24 hour)       1        75           0.1      0.08
off-peak 10 hour    20      2969           2.0      2.97
off-peak 7 hour     62      6275           6.2      6.28
single             660     58560          66.0     58.56
standard tariff    152     19331          15.2     19.33

>> Variable: FLOOR_DESCRIPTION

                                  Count           Percentage(%)
                                   Real Synthetic          Real Synthetic
FLOOR_DESCRIPTION
other premises below                224     23317          22.4     23.32
solid, insulated                      1        39           0.1      0.04
solid, insulated                     28      2936           2.8      2.94
solid, limited insulation            26      3184           2.6      3.18
solid, no insulation                464     45359          46.4     45.36
suspended, insulated                  3       138           0.3      0.14
suspended, insulated                 12      2017           1.2      2.02
suspended, limited insulation         3       160           0.3      0.16
suspended, no insulation            227     21859          22.7     21.86
to external air, insulated            1        29           0.1      0.03
to external air, no insulation        2        74           0.2      0.07
to unheated space, insulated          1        21           0.1      0.02
to unheated space, no insulation      8       867           0.8      0.87

>> Variable: GLAZED_AREA

                       Count           Percentage(%)
                        Real Synthetic          Real Synthetic
GLAZED_AREA
more than typical         22      4123           2.2      4.12
much more than typical     5      1251           0.5      1.25
normal                   973     94626          97.3     94.63

>> Variable: GLAZED_TYPE

                                      Count           Percentage(%)
                                       Real Synthetic          Real Synthetic
GLAZED_TYPE
double                                  604     61656          60.4     61.66
double installed before 2002            108     11040          10.8     11.04
double installed during or after 2002   286     27151          28.6     27.15
triple                                    2       153           0.2      0.15

>> Variable: HOTWATER_DESCRIPTION

                                              Count           Percentage(%)  \
                                               Real Synthetic          Real
HOTWATER_DESCRIPTION
community scheme                                 51      6585           5.1
community scheme, no cylinderstat                 1        51           0.1
electric immersion, off-peak                     68     12540           6.8
electric immersion, standard tariff              42      8171           4.2
electric instantaneous at point of use           15      2574           1.5
from main system                                771     63881          77.1
from main system, flue gas heat recovery          5      1146           0.5
from main system, no cylinderstat                35      3390           3.5
from main system, plus solar                      6      1100           0.6
from main system, waste water heat recovery       2       121           0.2
no system present: electric immersion assumed     4       441           0.4


                                              Synthetic
HOTWATER_DESCRIPTION
community scheme                                   6.59
community scheme, no cylinderstat                  0.05
electric immersion, off-peak                      12.54
electric immersion, standard tariff                8.17
electric instantaneous at point of use             2.57
from main system                                  63.88
from main system, flue gas heat recovery           1.15
from main system, no cylinderstat                  3.39
from main system, plus solar                       1.10
from main system, waste water heat recovery        0.12
no system present: electric immersion assumed      0.44

>> Variable: MAINHEATCONT_DESCRIPTION

                                                   Count            \
                                                    Real Synthetic
MAINHEATCONT_DESCRIPTION
appliance thermostats                                 17      3356
automatic charge control                               6      1052
charging system linked to use of community heat...     5      1145
charging system linked to use of community heat...     5      1179
charging system linked to use of community heat...     1        17
charging system linked to use of community heat...    13      1967
charging system linked to use of community heat...     3       110
controls for high heat retention storage heaters       5       553
flat rate charging, no thermostatic control of ...     3        94
flat rate charging, programmer and room thermostat     2        39
flat rate charging, programmer and trvs                5       745
flat rate charging, trvs                              14      1185
manual charge control                                 32      5765
no thermostatic control of room temperature            8      1260
no time or thermostatic control of room tempera...     5       472
programmer and appliance thermostats                  37      5994
programmer and at least two room thermostats           2        34
programmer and room thermostat                        85      7395
programmer and room thermostats                        2        44
programmer, no room thermostat                        29      3071
programmer, room thermostat and trvs                 535     46485
programmer, trvs and boiler energy manager             1        19
programmer, trvs and bypass                           84      7366
room thermostat only                                   8       936
time and temperature zone control                     84      8713
trvs and bypass                                        9      1004

                                                   Percentage(%)
                                                            Real Synthetic
MAINHEATCONT_DESCRIPTION
appliance thermostats                                        1.7      3.36
automatic charge control                                     0.6      1.05
charging system linked to use of community heat...           0.5      1.14
charging system linked to use of community heat...           0.5      1.18
charging system linked to use of community heat...           0.1      0.02
charging system linked to use of community heat...           1.3      1.97
charging system linked to use of community heat...           0.3      0.11
controls for high heat retention storage heaters             0.5      0.55
flat rate charging, no thermostatic control of ...           0.3      0.09
flat rate charging, programmer and room thermostat           0.2      0.04
flat rate charging, programmer and trvs                      0.5      0.74
flat rate charging, trvs                                     1.4      1.18
manual charge control                                        3.2      5.76
no thermostatic control of room temperature                  0.8      1.26
no time or thermostatic control of room tempera...           0.5      0.47
programmer and appliance thermostats                         3.7      5.99
programmer and at least two room thermostats                 0.2      0.03
programmer and room thermostat                               8.5      7.40
programmer and room thermostats                              0.2      0.04
programmer, no room thermostat                               2.9      3.07
programmer, room thermostat and trvs                        53.5     46.48
programmer, trvs and boiler energy manager                   0.1      0.02
programmer, trvs and bypass                                  8.4      7.37
room thermostat only                                         0.8      0.94
time and temperature zone control                            8.4      8.71
trvs and bypass                                              0.9      1.00

>> Variable: MAINHEAT_DESCRIPTION

                                                   Count            \
                                                    Real Synthetic
MAINHEAT_DESCRIPTION
air source heat pump, radiators, electric              5      1449
air source heat pump, underfloor, electric             2       136
boiler and radiators, bottled lpg                      1        48
boiler and radiators, coal                             1        37
boiler and radiators, dual fuel (mineral and wood)     1        57
boiler and radiators, electric                         6      1565
boiler and radiators, lpg                              5      1357
boiler and radiators, mains gas                      757     59571
boiler and radiators, oil                             33      4501
boiler and radiators, wood logs                        1        51
boiler and underfloor heating, electric                1        38
boiler and underfloor heating, mains gas               7      1580
boiler and underfloor heating, oil                     2       362
boiler and underfloor, mains gas                       2       204
community scheme                                      52      6961
electric ceiling heating                               1        61
electric storage heaters                              42      8958
electric underfloor heating                            2       177
ground source heat pump, radiators, electric           1        48
ground source heat pump, underfloor, electric          1        39
no system present: electric heaters assumed            4       823
portable electric heaters assumed for most rooms       2       192
room heaters, coal                                     1        39
room heaters, electric                                66     11489
room heaters, mains gas                                1        49
room heaters, wood logs                                1        54
warm air, electricaire                                 2       154

                                                   Percentage(%)
                                                            Real Synthetic
MAINHEAT_DESCRIPTION
air source heat pump, radiators, electric                    0.5      1.45
air source heat pump, underfloor, electric                   0.2      0.14
boiler and radiators, bottled lpg                            0.1      0.05
boiler and radiators, coal                                   0.1      0.04
boiler and radiators, dual fuel (mineral and wood)           0.1      0.06
boiler and radiators, electric                               0.6      1.57
boiler and radiators, lpg                                    0.5      1.36
boiler and radiators, mains gas                             75.7     59.57
boiler and radiators, oil                                    3.3      4.50
boiler and radiators, wood logs                              0.1      0.05
boiler and underfloor heating, electric                      0.1      0.04
boiler and underfloor heating, mains gas                     0.7      1.58
boiler and underfloor heating, oil                           0.2      0.36
boiler and underfloor, mains gas                             0.2      0.20
community scheme                                             5.2      6.96
electric ceiling heating                                     0.1      0.06
electric storage heaters                                     4.2      8.96
electric underfloor heating                                  0.2      0.18
ground source heat pump, radiators, electric                 0.1      0.05
ground source heat pump, underfloor, electric                0.1      0.04
no system present: electric heaters assumed                  0.4      0.82
portable electric heaters assumed for most rooms             0.2      0.19
room heaters, coal                                           0.1      0.04
room heaters, electric                                       6.6     11.49
room heaters, mains gas                                      0.1      0.05
room heaters, wood logs                                      0.1      0.05
warm air, electricaire                                       0.2      0.15

>> Variable: MAIN_FUEL

                                                   Count            \
                                                    Real Synthetic
MAIN_FUEL
dual fuel - mineral + wood                             2       124
electricity (not community)                          112     19916
electricity: electricity, unspecified tariff          21      4443
gas: mains gas                                        27      4050
house coal (not community)                             2       157
lpg (not community)                                    4       644
lpg - this is for backwards compatibility only ...     1        69
mains gas (community)                                 20      2068
mains gas (not community)                            703     54742
mains gas - this is for backwards compatibility...    70      7862
oil (not community)                                   35      5736
oil - this is for backwards compatibility only ...     1        69
to be used only when there is no heating/hot-wa...     2       120

                                                   Percentage(%)
                                                            Real Synthetic
MAIN_FUEL
dual fuel - mineral + wood                                   0.2      0.12
electricity (not community)                                 11.2     19.92
electricity: electricity, unspecified tariff                 2.1      4.44
gas: mains gas                                               2.7      4.05
house coal (not community)                                   0.2      0.16
lpg (not community)                                          0.4      0.64
lpg - this is for backwards compatibility only ...           0.1      0.07
mains gas (community)                                        2.0      2.07
mains gas (not community)                                   70.3     54.74
mains gas - this is for backwards compatibility...           7.0      7.86
oil (not community)                                          3.5      5.74
oil - this is for backwards compatibility only ...           0.1      0.07
to be used only when there is no heating/hot-wa...           0.2      0.12

>> Variable: MECHANICAL_VENTILATION

                               Count           Percentage(%)
                                Real Synthetic          Real Synthetic
MECHANICAL_VENTILATION
mechanical, extract only           3      1024           0.3      1.02
mechanical, supply and extract     3       767           0.3      0.77
natural                          994     98209          99.4     98.21

>> Variable: POSTTOWN

              Count           Percentage(%)
               Real Synthetic          Real Synthetic
POSTTOWN
aberdare          1         5           0.1      0.00
aberdovey         1         3           0.1      0.00
aberystwyth       1         3           0.1      0.00
abingdon          1         3           0.1      0.00
accrington        2       566           0.2      0.57
...             ...       ...           ...       ...
yarm              1         2           0.1      0.00
yelverton         1         1           0.1      0.00
yeovil            2       465           0.2      0.46
york              2         9           0.2      0.01
ystrad meurig     1         4           0.1      0.00

[432 rows x 4 columns]

>> Variable: POTENTIAL_ENERGY_RATING

                        Count           Percentage(%)
                         Real Synthetic          Real Synthetic
POTENTIAL_ENERGY_RATING
a                          79      9624           7.9      9.62
b                         528     50477          52.8     50.48
c                         349     33290          34.9     33.29
d                          40      6119           4.0      6.12
e                           4       490           0.4      0.49

>> Variable: PROPERTY_TYPE

              Count           Percentage(%)
               Real Synthetic          Real Synthetic
PROPERTY_TYPE
bungalow         82      8845           8.2      8.85
flat            318     32201          31.8     32.20
house           574     54671          57.4     54.67
maisonette       26      4283           2.6      4.28

>> Variable: ROOF_DESCRIPTION

                                    Count           Percentage(%)
                                     Real Synthetic          Real Synthetic
ROOF_DESCRIPTION
flat, insulated                         6       437           0.6      0.44
flat, limited insulation                9      1490           0.9      1.49
flat, no insulation                     7       942           0.7      0.94
other premises above                  310     33437          31.0     33.44
pitched, 100 mm loft insulation       102      9709          10.2      9.71
pitched, 150 mm loft insulation        84      7639           8.4      7.64
pitched, 200 mm loft insulation       118     11711          11.8     11.71
pitched, 25 mm loft insulation          1        21           0.1      0.02
pitched, 250 mm loft insulation        59      5203           5.9      5.20
pitched, 270 mm loft insulation        35      2929           3.5      2.93
pitched, 300 mm loft insulation        61      5811           6.1      5.81
pitched, 350 mm loft insulation         4       164           0.4      0.16
pitched, 400 mm loft insulation         5       233           0.5      0.23
pitched, 50 mm loft insulation         22      2272           2.2      2.27
pitched, 75 mm loft insulation         10      1470           1.0      1.47
pitched, insulated                     31      2762           3.1      2.76
pitched, insulated at rafters           5       215           0.5      0.22
pitched, limited insulation            17      2277           1.7      2.28
pitched, no insulation                 91      9205           9.1      9.20
roof rooms, ceiling insulated           4       153           0.4      0.15
roof rooms, insulated                   7       860           0.7      0.86
roof rooms, limited insulation          2        31           0.2      0.03
roof rooms, no insulation               9      1000           0.9      1.00
thatched with additional insulation     1        29           0.1      0.03

>> Variable: TENURE

                                                   Count            \
                                                    Real Synthetic
TENURE
not defined - use in the case of a new dwelling...    38      5626
owner-occupied                                       566     56359
rented (private)                                     236     22878
rented (social)                                      160     15137

                                                   Percentage(%)
                                                            Real Synthetic
TENURE
not defined - use in the case of a new dwelling...           3.8      5.63
owner-occupied                                              56.6     56.36
rented (private)                                            23.6     22.88
rented (social)                                             16.0     15.14

>> Variable: WALLS_DESCRIPTION

                                                   Count            \
                                                    Real Synthetic
WALLS_DESCRIPTION
cavity wall, filled cavity                           396     39325
cavity wall, filled cavity and internal insulation     1        30
cavity wall, insulated                               137     12506
cavity wall, no insulation                           116     10991
cavity wall, partial insulation                       30      4650
cob, as built                                          1        36
granite or whinstone, insulated                        1        32
granite or whinstone, no insulation                   15      1963
sandstone or limestone, insulated                      1        34
sandstone or limestone, no insulation                 30      3953
solid brick, insulated                                20      2116
solid brick, no insulation                           197     18482
solid brick, partial insulation                        1        29
system built, insulated                               21      1873
system built, no insulation                            9      1434
system built, partial insulation                       1        30
timber frame, insulated                               17      2254
timber frame, no insulation                            4       211
timber frame, partial insulation                       2        51

                                                   Percentage(%)
                                                            Real Synthetic
WALLS_DESCRIPTION
cavity wall, filled cavity                                  39.6     39.32
cavity wall, filled cavity and internal insulation           0.1      0.03
cavity wall, insulated                                      13.7     12.51
cavity wall, no insulation                                  11.6     10.99
cavity wall, partial insulation                              3.0      4.65
cob, as built                                                0.1      0.04
granite or whinstone, insulated                              0.1      0.03
granite or whinstone, no insulation                          1.5      1.96
sandstone or limestone, insulated                            0.1      0.03
sandstone or limestone, no insulation                        3.0      3.95
solid brick, insulated                                       2.0      2.12
solid brick, no insulation                                  19.7     18.48
solid brick, partial insulation                              0.1      0.03
system built, insulated                                      2.1      1.87
system built, no insulation                                  0.9      1.43
system built, partial insulation                             0.1      0.03
timber frame, insulated                                      1.7      2.25
timber frame, no insulation                                  0.4      0.21
timber frame, partial insulation                             0.2      0.05

>> Variable: WINDOWS_DESCRIPTION

                    Count           Percentage(%)
                     Real Synthetic          Real Synthetic
WINDOWS_DESCRIPTION
full double           756     67665          75.6     67.66
full triple             2       170           0.2      0.17
high performance      150     18997          15.0     19.00
mostly double          28      3872           2.8      3.87
partial double         27      3320           2.7      3.32
partial multiple        1        53           0.1      0.05
single                 27      3655           2.7      3.66
some double             9      2268           0.9      2.27

-- Anomalies Detected Across All Numeric Columns --

                                              Anomaly  Count  Percent
0   CO2_EMISSIONS_CURRENT below real min (0.200000...   2041     2.04
1   CO2_EMISSIONS_CURRENT above real max (21.60000...    258     0.26
2               CO2_EMISSIONS_CURRENT negative values   1033     1.03
3   CO2_EMISSIONS_POTENTIAL below real min (-1.600...    133     0.13
4       CO2_EMISSIONS_POTENTIAL above real max (10.0)    421     0.42
5      CURRENT_ENERGY_EFFICIENCY below real min (2.0)     61     0.06
6     CURRENT_ENERGY_EFFICIENCY above real max (93.0)     70     0.07
7           CURRENT_ENERGY_EFFICIENCY negative values     27     0.03
8             LAT below real min (-5.210899829864502)    380     0.38
9             LAT above real max (1.7395000457763672)    800     0.80
10          LIGHTING_DESCRIPTION below real min (0.0)   2672     2.67
11        LIGHTING_DESCRIPTION above real max (100.0)  24019    24.02
12               LIGHTING_DESCRIPTION negative values   2672     2.67
13            LONG below real min (50.12419891357422)    410     0.41
14            LONG above real max (55.82630157470703)    322     0.32
15           LOW_ENERGY_LIGHTING below real min (0.0)   3004     3.00
16         LOW_ENERGY_LIGHTING above real max (100.0)  23017    23.02
17                LOW_ENERGY_LIGHTING negative values   3004     3.00
18      MAIN_HEATING_CONTROLS below real min (2101.0)   3857     3.86
19      MAIN_HEATING_CONTROLS above real max (2706.0)    184     0.18
20        MULTI_GLAZE_PROPORTION below real min (0.0)   1466     1.47
21      MULTI_GLAZE_PROPORTION above real max (100.0)  40814    40.81
22             MULTI_GLAZE_PROPORTION negative values   1466     1.47
23  NB_MEAN_CO2_EMISSIONS_CURRENT below real min (...   1121     1.12
24      NB_MEAN_CO2_EMISSIONS_CURRENT negative values     22     0.02
25  NB_MEAN_CURRENT_ENERGY_EFFICIENCY below real m...    123     0.12
26  NB_MEAN_CURRENT_ENERGY_EFFICIENCY above real m...    562     0.56
27  NB_MEAN_CURRENT_ENERGY_EFFICIENCY negative values    108     0.11
28  NB_MEAN_POTENTIAL_ENERGY_EFFICIENCY below real...     44     0.04
29  NB_MEAN_POTENTIAL_ENERGY_EFFICIENCY above real...     10     0.01
30  NB_MEAN_POTENTIAL_ENERGY_EFFICIENCY negative v...     37     0.04
31   NB_SD_CO2_EMISSIONS_CURRENT below real min (0.0)   8766     8.77
32  NB_SD_CO2_EMISSIONS_CURRENT above real max (19...     44     0.04
33        NB_SD_CO2_EMISSIONS_CURRENT negative values   8766     8.77
34  NB_SD_CURRENT_ENERGY_EFFICIENCY below real min...   4399     4.40
35  NB_SD_CURRENT_ENERGY_EFFICIENCY above real max...    258     0.26
36    NB_SD_CURRENT_ENERGY_EFFICIENCY negative values   4399     4.40
37  NB_SD_CURRENT_ENERGY_RATING above real max (2....   3004     3.00
38  NB_SD_POTENTIAL_ENERGY_EFFICIENCY below real m...   8655     8.65
39  NB_SD_POTENTIAL_ENERGY_EFFICIENCY above real m...    488     0.49
40  NB_SD_POTENTIAL_ENERGY_EFFICIENCY negative values   8655     8.65
41   POSTCODE_LAT below real min (-5.210899829864502)    283     0.28
42   POSTCODE_LAT above real max (1.7395000457763672)    510     0.51
43   POSTCODE_LONG below real min (50.12419891357422)    358     0.36
44   POSTCODE_LONG above real max (55.82630157470703)    221     0.22
45  POTENTIAL_ENERGY_EFFICIENCY below real min (42.0)     49     0.05
46  POTENTIAL_ENERGY_EFFICIENCY above real max (12...    118     0.12
47             TOTAL_FLOOR_AREA below real min (14.0)    879     0.88
48                   TOTAL_FLOOR_AREA negative values     44     0.04

-- Generating Histograms --
-- Generating Violin Plots --
-- Generating Heatmaps --


=== Analyzing Income Dataset ===
Dimension of real data: (5000, 51)
Dimension of synthetic data: (100000, 51)
Numeric columns detected (47): ['10DAILY TRAVEL', '11TRAVEL MODE', '12CONSCIOUS', '13ACCOUNTS', '14SUM', '15MOBILE', '16MOBTIME', '17CAR', '18INTERNET', '19SPORT', '1SIBLING', '20VEGAN', '21CIVIL', '22POLIT', '23ILL', '24MEDICINE', '25DOCTOR', '26COVID', '27ADVERT', '28CULTURE', '29FOOD', '2HOME', '30CHILDREN', '31ROOMS', '32VALUABLES', '33CLOTHS', '34JEWELS', '35SMOKE', '36ALCOHOL', '37MUSIC', '38FACE', '39TWITTER', '3EDUC', '40ONLINE1', '41ONLINE2', '42TV', '43REFURB', '44MOVE', '45TRAVDEST', '4TRAVEL', '5CREDIT', '6CR SUM', '7CARD', '8PASTIME', '9CHANGES', 'AGE', 'HEIGHT']

-- Metadata Comparison --

          Variable Real_dtype Synthetic_dtype  Type_Match
0     INCOME_LEVEL     object          object        True
1              SEX     object          object        True
2              AGE      int64         float64       False
3             TOWN     object          object        True
4       OCCUPATION     object          object        True
5           HEIGHT      int64         float64       False
6         1SIBLING      int64           int64        True
7            2HOME      int64           int64        True
8            3EDUC      int64           int64        True
9          4TRAVEL      int64           int64        True
10         5CREDIT      int64           int64        True
11         6CR SUM      int64           int64        True
12           7CARD      int64           int64        True
13        8PASTIME      int64           int64        True
14        9CHANGES      int64           int64        True
15  10DAILY TRAVEL      int64         float64       False
16   11TRAVEL MODE      int64           int64        True
17     12CONSCIOUS      int64           int64        True
18      13ACCOUNTS      int64           int64        True
19           14SUM      int64         float64       False
20        15MOBILE      int64           int64        True
21       16MOBTIME      int64           int64        True
22           17CAR      int64           int64        True
23      18INTERNET      int64           int64        True
24         19SPORT      int64           int64        True
25         20VEGAN      int64           int64        True
26         21CIVIL      int64           int64        True
27         22POLIT      int64           int64        True
28           23ILL      int64           int64        True
29      24MEDICINE      int64           int64        True
30        25DOCTOR      int64           int64        True
31         26COVID      int64           int64        True
32        27ADVERT      int64           int64        True
33       28CULTURE      int64           int64        True
34          29FOOD      int64           int64        True
35      30CHILDREN      int64           int64        True
36         31ROOMS      int64           int64        True
37     32VALUABLES      int64         float64       False
38        33CLOTHS      int64           int64        True
39        34JEWELS      int64           int64        True
40         35SMOKE      int64           int64        True
41       36ALCOHOL      int64           int64        True
42         37MUSIC      int64           int64        True
43          38FACE      int64           int64        True
44       39TWITTER      int64           int64        True
45       40ONLINE1      int64           int64        True
46       41ONLINE2      int64           int64        True
47            42TV      int64           int64        True
48        43REFURB      int64           int64        True
49          44MOVE      int64           int64        True
50      45TRAVDEST      int64           int64        True

-- Range Comparison for Numeric Variables --

,Variable,Real_Min,Real_Max,Synthetic_Min,Synthetic_Max,Range_Expanded
0,10DAILY TRAVEL,0,18,-0.100054,1.365220e+01,True
1,11TRAVEL MODE,0,4,0.000000,4.000000e+00,False
2,12CONSCIOUS,0,1,0.000000,1.000000e+00,False
3,13ACCOUNTS,0,1,0.000000,1.000000e+00,False
4,14SUM,0,20006400,-241364.711200,2.107659e+07,True
5,15MOBILE,0,1,0.000000,1.000000e+00,False
6,16MOBTIME,0,1,0.000000,1.000000e+00,False
7,17CAR,0,1,0.000000,1.000000e+00,False
8,18INTERNET,0,1,0.000000,1.000000e+00,False
9,19SPORT,0,1,0.000000,1.000000e+00,False
10,1SIBLING,0,4,0.000000,4.000000e+00,False
11,20VEGAN,0,1,0.000000,1.000000e+00,False
12,21CIVIL,0,1,0.000000,1.000000e+00,False
13,22POLIT,0,1,0.000000,1.000000e+00,False
14,23ILL,0,1,0.000000,1.000000e+00,False
15,24MEDICINE,0,1,0.000000,1.000000e+00,False
16,25DOCTOR,0,5,0.000000,5.000000e+00,False
17,26COVID,0,3,0.000000,3.000000e+00,False
18,27ADVERT,0,1,0.000000,1.000000e+00,False
19,28CULTURE,0,4,0.000000,4.000000e+00,False
20,29FOOD,0,4,0.000000,4.000000e+00,False
21,2HOME,0,2,0.000000,2.000000e+00,False
22,30CHILDREN,0,4,0.000000,4.000000e+00,False
23,31ROOMS,0,4,0.000000,4.000000e+00,False
24,32VALUABLES,0,92440,-385.787696,1.181508e+05,True
25,33CLOTHS,0,3,0.000000,3.000000e+00,False
26,34JEWELS,0,3,0.000000,3.000000e+00,False
27,35SMOKE,0,1,0.000000,1.000000e+00,False
28,36ALCOHOL,0,3,0.000000,3.000000e+00,False
29,37MUSIC,0,3,0.000000,3.000000e+00,False
30,38FACE,0,1,0.000000,1.000000e+00,False
31,39TWITTER,0,1,0.000000,1.000000e+00,False
32,3EDUC,0,4,0.000000,4.000000e+00,False
33,40ONLINE1,0,2,0.000000,2.000000e+00,False
34,41ONLINE2,0,2,0.000000,2.000000e+00,False
35,42TV,0,2,0.000000,2.000000e+00,False
36,43REFURB,0,1,0.000000,1.000000e+00,False
37,44MOVE,0,1,0.000000,1.000000e+00,False
38,45TRAVDEST,0,4,0.000000,4.000000e+00,False
39,4TRAVEL,0,1,0.000000,1.000000e+00,False
40,5CREDIT,0,1,0.000000,1.000000e+00,False
41,6CR SUM,0,3,0.000000,3.000000e+00,False
42,7CARD,0,1,0.000000,1.000000e+00,False
43,8PASTIME,0,14,0.000000,1.400000e+01,False
44,9CHANGES,0,3,0.000000,3.000000e+00,False
45,AGE,25,65,20.524862,6.970343e+01,True
46,HEIGHT,147,203,143.728459,2.063562e+02,True

Metadata Summary:
• Both datasets contain:
  o 47 numeric variables
  o 21 binary outcome variable(s)
• WARNING: Some variable types differ between real and synthetic datasets!
      Variable Real_dtype Synthetic_dtype  Type_Match
           AGE      int64         float64       False
        HEIGHT      int64         float64       False
10DAILY TRAVEL      int64         float64       False
         14SUM      int64         float64       False
   32VALUABLES      int64         float64       False
• The synthetic dataset expands the range of the following variable(s): ['10DAILY TRAVEL', '14SUM', '32VALUABLES', 'AGE', 'HEIGHT']

-- Real Data Descriptive Statistics --

,Statistic,10DAILY TRAVEL,11TRAVEL MODE,12CONSCIOUS,13ACCOUNTS,14SUM,15MOBILE,16MOBTIME,17CAR,18INTERNET,...,44MOVE,45TRAVDEST,4TRAVEL,5CREDIT,6CR SUM,7CARD,8PASTIME,9CHANGES,AGE,HEIGHT
0,Count,5000.00,5000.00,5000.00,5000.00,5000.00,5000.00,5000.00,5000.00,5000.00,...,5000.00,5000.00,5000.00,5000.00,5000.00,5000.00,5000.00,5000.00,5000.0,5000.00
1,Mean,2.36,1.19,0.02,0.42,412870.54,0.71,0.15,0.34,0.18,...,0.41,1.62,0.72,0.98,1.17,0.92,1.65,1.98,44.4,170.07
2,Std Dev,2.57,1.48,0.12,0.49,1851002.55,0.45,0.35,0.47,0.38,...,0.49,1.13,0.45,0.14,0.44,0.27,1.32,0.91,11.9,8.77
3,Min,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,25.0,147.00
4,Median,2.00,1.00,0.00,0.00,109553.50,1.00,0.00,0.00,0.00,...,0.00,1.00,1.00,1.00,1.00,1.00,1.00,2.00,45.0,169.00
5,Max,18.00,4.00,1.00,1.00,20006400.00,1.00,1.00,1.00,1.00,...,1.00,4.00,1.00,1.00,3.00,1.00,14.00,3.00,65.0,203.00

-- Synthetic Data Descriptive Statistics --

,Statistic,10DAILY TRAVEL,11TRAVEL MODE,12CONSCIOUS,13ACCOUNTS,14SUM,15MOBILE,16MOBTIME,17CAR,18INTERNET,...,44MOVE,45TRAVDEST,4TRAVEL,5CREDIT,6CR SUM,7CARD,8PASTIME,9CHANGES,AGE,HEIGHT
0,Count,100000.00,100000.00,100000.00,100000.00,100000.00,100000.00,100000.00,100000.00,100000.00,...,100000.00,100000.00,100000.00,100000.00,100000.00,100000.00,100000.00,100000.00,100000.00,100000.00
1,Mean,2.34,1.23,0.03,0.42,432559.83,0.72,0.16,0.33,0.18,...,0.40,1.62,0.73,0.96,1.17,0.91,1.62,1.96,44.47,170.35
2,Std Dev,2.46,1.49,0.17,0.49,1924907.95,0.45,0.36,0.47,0.38,...,0.49,1.13,0.45,0.19,0.45,0.29,1.19,0.93,11.97,9.08
3,Min,-0.10,0.00,0.00,0.00,-241364.71,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,20.52,143.73
4,Median,1.98,1.00,0.00,0.00,106602.18,1.00,0.00,0.00,0.00,...,0.00,1.00,1.00,1.00,1.00,1.00,1.00,2.00,44.64,169.74
5,Max,13.65,4.00,1.00,1.00,21076592.61,1.00,1.00,1.00,1.00,...,1.00,4.00,1.00,1.00,3.00,1.00,14.00,3.00,69.70,206.36

-- Categorical Variable Distributions --

>> Variable: INCOME_LEVEL

             Count           Percentage(%)
              Real Synthetic          Real Synthetic
INCOME_LEVEL
l0            2171     43877         43.42     43.88
l1            2829     56123         56.58     56.12

>> Variable: OCCUPATION

           Count           Percentage(%)
            Real Synthetic          Real Synthetic
OCCUPATION
Lakatos     1691     34254         33.82     34.25
Szakorvos   1627     32588         32.54     32.59
asztalos    1682     33158         33.64     33.16

>> Variable: SEX

       Count           Percentage(%)
        Real Synthetic          Real Synthetic
SEX
female  1368     27221         27.36     27.22
male    3632     72779         72.64     72.78

>> Variable: TOWN

            Count           Percentage(%)
             Real Synthetic          Real Synthetic
TOWN
Budakeszi    1872     37907         37.44     37.91
Nagybajcs     628     12645         12.56     12.65
Nagykanizsa  2500     49448         50.00     49.45

-- Anomalies Detected Across All Numeric Columns --

                               Anomaly  Count  Percent
0    10DAILY TRAVEL below real min (0)  16102    16.10
1       10DAILY TRAVEL negative values  16102    16.10
2             14SUM below real min (0)  15145    15.14
3      14SUM above real max (20006400)     14     0.01
4                14SUM negative values  15145    15.14
5       32VALUABLES below real min (0)  11501    11.50
6   32VALUABLES above real max (92440)    105     0.10
7          32VALUABLES negative values  11501    11.50
8              AGE below real min (25)   2737     2.74
9              AGE above real max (65)   1290     1.29
10         HEIGHT below real min (147)     70     0.07
11         HEIGHT above real max (203)     19     0.02

-- Generating Histograms --
-- Generating Violin Plots --
-- Generating Heatmaps --


=== Analyzing Pollution Dataset ===
Dimension of real data: (36500, 5)
Dimension of synthetic data: (365000, 4)
Numeric columns detected (4): ['client', 'pollution', 'risk', 'wind']

-- Metadata Comparison --

    Variable Real_dtype Synthetic_dtype  Type_Match
0     client      int64           int64        True
1  pollution    float64         float64        True
2       risk    float64         float64        True
3       time      int64             NaN       False
4       wind    float64         float64        True

-- Range Comparison for Numeric Variables --

    Variable  Real_Min  Real_Max  Synthetic_Min  Synthetic_Max  Range_Expanded
0     client     1.000   100.000     101.000000    1100.000000            True
1  pollution     0.001     8.497       0.014003       7.076798           False
2       risk     0.043     5.520       0.076043       4.272171           False
3       wind     0.000  3925.250       0.001768    2312.333984           False

Metadata Summary:
• Both datasets contain:
  o 4 numeric variables
  o 0 binary outcome variable(s)
• WARNING: Some variable types differ between real and synthetic datasets!
Variable Real_dtype Synthetic_dtype  Type_Match
    time      int64             NaN       False
• The synthetic dataset expands the range of the following variable(s): ['client']

-- Real Data Descriptive Statistics --

  Statistic    client  pollution      risk      wind
0     Count  36500.00   36500.00  36500.00  36500.00
1      Mean     50.50       1.16      1.69     18.98
2   Std Dev     28.87       0.94      1.23     94.12
3       Min      1.00       0.00      0.04      0.00
4    Median     50.50       1.00      1.40      1.07
5       Max    100.00       8.50      5.52   3925.25

-- Synthetic Data Descriptive Statistics --

  Statistic     client  pollution       risk       wind
0     Count  365000.00  365000.00  365000.00  365000.00
1      Mean     600.50       1.18       1.60      21.78
2   Std Dev     288.68       1.04       1.05      45.94
3       Min     101.00       0.01       0.08       0.00
4    Median     600.50       0.85       1.35       7.69
5       Max    1100.00       7.08       4.27    2312.33

-- Categorical Variable Distributions --
No shared categorical variables found in both datasets.

-- Anomalies Detected Across All Numeric Columns --

                       Anomaly   Count  Percent
0  client above real max (100)  365000    100.0

-- Generating Histograms --
-- Generating Violin Plots --
-- Generating Heatmaps --


=== Analyzing Wine Dataset ===
Dimension of real data: (1599, 12)
Dimension of synthetic data: (500000, 12)
Numeric columns detected (12): ['ALCOHOL', 'CHLORIDES', 'CITRIC ACID', 'DENSITY', 'FIXED ACIDITY', 'FREE SULFUR DIOXIDE', 'PH', 'QUALITY', 'RESIDUAL SUGAR', 'SULPHATES', 'TOTAL SULFUR DIOXIDE', 'VOLATILE ACIDITY']

-- Metadata Comparison --

                Variable Real_dtype Synthetic_dtype  Type_Match
0          FIXED ACIDITY    float64         float64        True
1       VOLATILE ACIDITY    float64         float64        True
2            CITRIC ACID    float64         float64        True
3         RESIDUAL SUGAR    float64         float64        True
4              CHLORIDES    float64         float64        True
5    FREE SULFUR DIOXIDE    float64         float64        True
6   TOTAL SULFUR DIOXIDE    float64         float64        True
7                DENSITY    float64         float64        True
8                     PH    float64         float64        True
9              SULPHATES    float64         float64        True
10               ALCOHOL    float64         float64        True
11               QUALITY      int64           int64        True

-- Range Comparison for Numeric Variables --

,Variable,Real_Min,Real_Max,Synthetic_Min,Synthetic_Max,Range_Expanded
0,ALCOHOL,8.40000,14.90000,7.778243,15.001248,True
1,CHLORIDES,0.01200,0.61100,-0.091867,0.708657,True
2,CITRIC ACID,0.00000,1.00000,-0.167243,0.967889,True
3,DENSITY,0.99007,1.00369,0.989589,1.003844,True
4,FIXED ACIDITY,4.60000,15.90000,3.728328,18.700320,True
5,FREE SULFUR DIOXIDE,1.00000,72.00000,-5.659802,86.333673,True
6,PH,2.74000,4.01000,2.658622,4.244903,True
7,QUALITY,3.00000,8.00000,3.000000,8.000000,False
8,RESIDUAL SUGAR,0.90000,15.50000,-2.625121,21.923950,True
9,SULPHATES,0.33000,2.00000,0.021032,2.774487,True
10,TOTAL SULFUR DIOXIDE,6.00000,289.00000,-7.784020,196.727426,True
11,VOLATILE ACIDITY,0.12000,1.58000,-0.077438,1.800130,True

Metadata Summary:
• Both datasets contain:
  o 12 numeric variables
  o 0 binary outcome variable(s)
• Variable types are identical (floats or integers).
• The synthetic dataset expands the range of the following variable(s): ['ALCOHOL', 'CHLORIDES', 'CITRIC ACID', 'DENSITY', 'FIXED ACIDITY', 'FREE SULFUR DIOXIDE', 'PH', 'RESIDUAL SUGAR', 'SULPHATES', 'TOTAL SULFUR DIOXIDE', 'VOLATILE ACIDITY']

-- Real Data Descriptive Statistics --

,Statistic,ALCOHOL,CHLORIDES,CITRIC ACID,DENSITY,FIXED ACIDITY,FREE SULFUR DIOXIDE,PH,QUALITY,RESIDUAL SUGAR,SULPHATES,TOTAL SULFUR DIOXIDE,VOLATILE ACIDITY
0,Count,1599.00,1599.00,1599.00,1599.00,1599.00,1599.00,1599.00,1599.00,1599.00,1599.00,1599.00,1599.00
1,Mean,10.42,0.09,0.27,1.00,8.32,15.87,3.31,5.64,2.54,0.66,46.47,0.53
2,Std Dev,1.07,0.05,0.19,0.00,1.74,10.46,0.15,0.81,1.41,0.17,32.90,0.18
3,Min,8.40,0.01,0.00,0.99,4.60,1.00,2.74,3.00,0.90,0.33,6.00,0.12
4,Median,10.20,0.08,0.26,1.00,7.90,14.00,3.31,6.00,2.20,0.62,38.00,0.52
5,Max,14.90,0.61,1.00,1.00,15.90,72.00,4.01,8.00,15.50,2.00,289.00,1.58

-- Synthetic Data Descriptive Statistics --

,Statistic,ALCOHOL,CHLORIDES,CITRIC ACID,DENSITY,FIXED ACIDITY,FREE SULFUR DIOXIDE,PH,QUALITY,RESIDUAL SUGAR,SULPHATES,TOTAL SULFUR DIOXIDE,VOLATILE ACIDITY
0,Count,500000.00,500000.00,500000.00,500000.00,500000.00,500000.00,500000.00,500000.00,500000.00,500000.00,500000.00,500000.00
1,Mean,10.37,0.09,0.27,1.00,8.37,16.06,3.31,5.40,2.44,0.65,45.00,0.54
2,Std Dev,1.02,0.04,0.20,0.00,1.76,10.67,0.16,1.32,1.32,0.16,30.77,0.19
3,Min,7.78,-0.09,-0.17,0.99,3.73,-5.66,2.66,3.00,-2.63,0.02,-7.78,-0.08
4,Median,10.14,0.08,0.25,1.00,7.94,13.85,3.31,6.00,2.13,0.62,37.27,0.52
5,Max,15.00,0.71,0.97,1.00,18.70,86.33,4.24,8.00,21.92,2.77,196.73,1.80

-- Categorical Variable Distributions --
No shared categorical variables found in both datasets.

-- Anomalies Detected Across All Numeric Columns --

                                      Anomaly  Count  Percent
0                ALCOHOL below real min (8.4)     57     0.01
1               ALCOHOL above real max (14.9)      2     0.00
2            CHLORIDES below real min (0.012)     49     0.01
3            CHLORIDES above real max (0.611)     92     0.02
4                   CHLORIDES negative values     26     0.01
5            CITRIC ACID below real min (0.0)  24355     4.87
6                 CITRIC ACID negative values  24355     4.87
7            DENSITY below real min (0.99007)      4     0.00
8            DENSITY above real max (1.00369)      3     0.00
9          FIXED ACIDITY below real min (4.6)    234     0.05
10        FIXED ACIDITY above real max (15.9)    598     0.12
11   FREE SULFUR DIOXIDE below real min (1.0)    738     0.15
12  FREE SULFUR DIOXIDE above real max (72.0)    157     0.03
13        FREE SULFUR DIOXIDE negative values     94     0.02
14                   PH below real min (2.74)     25     0.00
15                   PH above real max (4.01)    269     0.05
16        RESIDUAL SUGAR below real min (0.9)    255     0.05
17       RESIDUAL SUGAR above real max (15.5)    384     0.08
18             RESIDUAL SUGAR negative values     63     0.01
19            SULPHATES below real min (0.33)     76     0.02
20             SULPHATES above real max (2.0)    357     0.07
21  TOTAL SULFUR DIOXIDE below real min (6.0)   7488     1.50
22       TOTAL SULFUR DIOXIDE negative values    423     0.08
23     VOLATILE ACIDITY below real min (0.12)    124     0.02
24     VOLATILE ACIDITY above real max (1.58)    165     0.03
25           VOLATILE ACIDITY negative values      1     0.00

-- Generating Histograms --
-- Generating Violin Plots --
-- Generating Heatmaps --


=== Analyzing Macroenv Dataset ===
Dimension of real data: (3000, 23)
Dimension of synthetic data: (30000, 24)
Numeric columns detected (23): ['CPIAUCSL', 'CPIAUCSL_prev_state', 'GDPC1', 'GDPC1_prev_state', 'TERMCBAUTO48NS', 'TERMCBAUTO48NS_prev_state', 'UNRATE', 'UNRATE_prev_state', 'btc', 'btc_prev_state_last_1', 'day', 'day_prev_state_last_1', 'doge', 'doge_prev_state_last_1', 'eth', 'eth_prev_state_last_1', 'id', 'month', 'month_prev_state_last_1', 'usdt', 'usdt_prev_state_last_1', 'year', 'year_prev_state_last_1']

-- Metadata Comparison --

                     Variable Real_dtype Synthetic_dtype  Type_Match
0                    CPIAUCSL    float64         float64        True
1         CPIAUCSL_prev_state    float64         float64        True
2                       GDPC1    float64         float64        True
3            GDPC1_prev_state    float64         float64        True
4              TERMCBAUTO48NS    float64         float64        True
5   TERMCBAUTO48NS_prev_state    float64         float64        True
6                      UNRATE    float64         float64        True
7           UNRATE_prev_state    float64         float64        True
8                  Unnamed: 0        NaN           int64       False
9                         btc    float64         float64        True
10      btc_prev_state_last_1    float64         float64        True
11                        day      int64           int64        True
12      day_prev_state_last_1      int64         float64       False
13                       doge    float64         float64        True
14     doge_prev_state_last_1    float64         float64        True
15                        eth    float64         float64        True
16      eth_prev_state_last_1    float64         float64        True
17                         id      int64         float64       False
18                      month      int64           int64        True
19    month_prev_state_last_1      int64         float64       False
20                       usdt    float64         float64        True
21     usdt_prev_state_last_1    float64         float64        True
22                       year      int64           int64        True
23     year_prev_state_last_1      int64         float64       False

-- Range Comparison for Numeric Variables --

,Variable,Real_Min,Real_Max,Synthetic_Min,Synthetic_Max,Range_Expanded
0,CPIAUCSL,237.336000,308.850000,238.402603,305.079041,False
1,CPIAUCSL_prev_state,237.336000,308.850000,237.336075,308.845093,False
2,GDPC1,18892.206000,22490.692000,18892.347656,22490.548828,False
3,GDPC1_prev_state,18892.206000,22490.692000,18892.248047,22490.503906,False
4,TERMCBAUTO48NS,4.000000,8.510000,4.001210,8.509386,False
5,TERMCBAUTO48NS_prev_state,4.000000,8.510000,4.001390,8.508606,False
6,UNRATE,3.430000,14.480000,3.430018,12.924187,False
7,UNRATE_prev_state,3.430000,14.480000,3.430016,13.294791,False
8,btc,-6924.210173,7474.233857,-5032.329102,5647.557617,False
9,btc_prev_state_last_1,325.800600,58817.373890,325.856182,54917.036483,False
10,day,1.000000,31.000000,1.000000,31.000000,False
11,day_prev_state_last_1,1.000000,31.000000,1.000000,31.000000,False
12,doge,-0.140236,0.194298,-0.067154,0.051465,False
13,doge_prev_state_last_1,0.000133,0.338777,0.000133,0.320152,False
14,eth,-894.034334,520.122258,-389.110291,287.689392,False
15,eth_prev_state_last_1,0.869488,4075.031619,1.065082,3975.417162,False
16,id,2.000000,101.000000,102.000000,1101.000000,True
17,month,1.000000,12.000000,1.000000,12.000000,False
18,month_prev_state_last_1,1.000000,12.000000,1.000000,12.000000,False
19,usdt,-0.326453,0.130887,-0.195183,0.075593,False
20,usdt_prev_state_last_1,0.941889,1.134962,0.975885,1.028079,False
21,year,2015.000000,2024.000000,2015.000000,2024.000000,False
22,year_prev_state_last_1,2015.000000,2023.000000,2015.000000,2023.000000,False

Metadata Summary:
• Both datasets contain:
  o 23 numeric variables
  o 0 binary outcome variable(s)
• WARNING: Some variable types differ between real and synthetic datasets!
               Variable Real_dtype Synthetic_dtype  Type_Match
             Unnamed: 0        NaN           int64       False
  day_prev_state_last_1      int64         float64       False
                     id      int64         float64       False
month_prev_state_last_1      int64         float64       False
 year_prev_state_last_1      int64         float64       False
• The synthetic dataset expands the range of the following variable(s): ['id']

-- Real Data Descriptive Statistics --

,Statistic,CPIAUCSL,CPIAUCSL_prev_state,GDPC1,GDPC1_prev_state,TERMCBAUTO48NS,TERMCBAUTO48NS_prev_state,UNRATE,UNRATE_prev_state,btc,...,doge_prev_state_last_1,eth,eth_prev_state_last_1,id,month,month_prev_state_last_1,usdt,usdt_prev_state_last_1,year,year_prev_state_last_1
0,Count,3000.00,3000.00,3000.00,3000.00,3000.00,3000.00,3000.00,3000.00,3000.00,...,3000.00,3000.00,3000.00,3000.00,3000.0,3000.00,3000.00,3000.00,3000.00,3000.00
1,Mean,264.56,264.09,20652.66,20616.68,5.32,5.28,4.69,4.70,14.09,...,0.05,0.84,921.45,51.50,6.6,6.61,-0.00,1.00,2019.43,2019.38
2,Std Dev,22.08,21.84,1094.24,1092.38,1.09,1.05,1.83,1.82,840.72,...,0.08,64.78,1046.62,28.87,3.5,3.49,0.01,0.02,2.37,2.38
3,Min,237.34,237.34,18892.21,18892.21,4.00,4.00,3.43,3.43,-6924.21,...,0.00,-894.03,0.87,2.00,1.0,1.00,-0.33,0.94,2015.00,2015.00
4,Median,256.99,256.75,20584.53,20558.77,5.12,5.11,4.02,4.04,3.25,...,0.00,0.03,347.33,51.50,7.0,7.00,0.00,1.00,2019.00,2019.00
5,Max,308.85,308.85,22490.69,22490.69,8.51,8.51,14.48,14.48,7474.23,...,0.34,520.12,4075.03,101.00,12.0,12.00,0.13,1.13,2024.00,2023.00

-- Synthetic Data Descriptive Statistics --

,Statistic,CPIAUCSL,CPIAUCSL_prev_state,GDPC1,GDPC1_prev_state,TERMCBAUTO48NS,TERMCBAUTO48NS_prev_state,UNRATE,UNRATE_prev_state,btc,...,doge_prev_state_last_1,eth,eth_prev_state_last_1,id,month,month_prev_state_last_1,usdt,usdt_prev_state_last_1,year,year_prev_state_last_1
0,Count,30000.00,30000.00,30000.00,30000.00,30000.00,30000.00,30000.00,30000.00,30000.00,...,30000.00,30000.00,30000.00,30000.00,30000.00,30000.00,30000.00,30000.00,30000.00,30000.00
1,Mean,264.12,264.71,20640.70,20622.05,5.35,5.32,4.58,4.63,22.20,...,0.04,-10.97,795.96,601.50,6.81,6.75,-0.01,1.00,2019.44,2019.38
2,Std Dev,19.82,21.38,1036.75,1043.62,1.08,1.05,1.46,1.53,788.35,...,0.07,66.22,987.37,288.68,3.63,3.66,0.01,0.01,2.39,2.38
3,Min,238.40,237.34,18892.35,18892.25,4.00,4.00,3.43,3.43,-5032.33,...,0.00,-389.11,1.07,102.00,1.00,1.00,-0.20,0.98,2015.00,2015.00
4,Median,256.70,258.81,20595.27,20615.82,5.11,5.09,4.07,4.10,18.58,...,0.01,-9.51,321.04,601.50,7.00,7.00,-0.00,1.00,2019.00,2019.00
5,Max,305.08,308.85,22490.55,22490.50,8.51,8.51,12.92,13.29,5647.56,...,0.32,287.69,3975.42,1101.00,12.00,12.00,0.08,1.03,2024.00,2023.00

-- Categorical Variable Distributions --
No shared categorical variables found in both datasets.

-- Anomalies Detected Across All Numeric Columns --

                   Anomaly  Count  Percent
0  id above real max (101)  30000    100.0

-- Generating Histograms --
-- Generating Violin Plots --
-- Generating Heatmaps --